In [9]:
import pandas as pd
import requests as req

In [2]:
r"T/6381/P/ALL/V/4099/N1/1"

'T/6381/P/ALL/V/4099/N1/1'

In [3]:
code=r"T/6381/P/ALL/V/4099/N1/1"

In [4]:
BASE_URL = 'https://apisidra.ibge.gov.br/'
format_suffix = f"values/{code}?formato=json"
req_url=BASE_URL + format_suffix

In [5]:
req_url

'https://apisidra.ibge.gov.br/values/T/6381/P/ALL/V/4099/N1/1?formato=json'

In [6]:
response = req.get(req_url)

In [7]:
response.json()

[{'NC': 'Nível Territorial (Código)',
  'NN': 'Nível Territorial',
  'MC': 'Unidade de Medida (Código)',
  'MN': 'Unidade de Medida',
  'V': 'Valor',
  'D1C': 'Trimestre Móvel (Código)',
  'D1N': 'Trimestre Móvel',
  'D2C': 'Variável (Código)',
  'D2N': 'Variável',
  'D3C': 'Brasil (Código)',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '8.0',
  'D1C': '201203',
  'D1N': 'jan-fev-mar 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.8',
  'D1C': '201204',
  'D1N': 'fev-mar-abr 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.7',
  'D1C': '201205',
  'D1N': 'mar-abr-mai 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.6',
  'D1C': '201206',
  'D1N': 'abr-mai-jun 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.5',
  'D1C': '201207',
  'D1N': 'mai-jun-jul 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.3',
  'D1C': '201208',
  'D1N': 'jun-jul-ago 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.1',
  'D1C': '201209',
  'D1N': 'jul-ago-set 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.9',
  'D1C': '201210',
  'D1N': 'ago-set-out 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.8',
  'D1C': '201211',
  'D1N': 'set-out-nov 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.9',
  'D1C': '201212',
  'D1N': 'out-nov-dez 2012',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.2',
  'D1C': '201301',
  'D1N': 'nov-dez-jan 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.8',
  'D1C': '201302',
  'D1N': 'dez-jan-fev 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '8.0',
  'D1C': '201303',
  'D1N': 'jan-fev-mar 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.9',
  'D1C': '201304',
  'D1N': 'fev-mar-abr 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.6',
  'D1C': '201305',
  'D1N': 'mar-abr-mai 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.5',
  'D1C': '201306',
  'D1N': 'abr-mai-jun 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.4',
  'D1C': '201307',
  'D1N': 'mai-jun-jul 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.2',
  'D1C': '201308',
  'D1N': 'jun-jul-ago 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.0',
  'D1C': '201309',
  'D1N': 'jul-ago-set 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.8',
  'D1C': '201310',
  'D1N': 'ago-set-out 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.5',
  'D1C': '201311',
  'D1N': 'set-out-nov 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.2',
  'D1C': '201312',
  'D1N': 'out-nov-dez 2013',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.5',
  'D1C': '201401',
  'D1N': 'nov-dez-jan 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.8',
  'D1C': '201402',
  'D1N': 'dez-jan-fev 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.2',
  'D1C': '201403',
  'D1N': 'jan-fev-mar 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.2',
  'D1C': '201404',
  'D1N': 'fev-mar-abr 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.0',
  'D1C': '201405',
  'D1N': 'mar-abr-mai 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.9',
  'D1C': '201406',
  'D1N': 'abr-mai-jun 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.0',
  'D1C': '201407',
  'D1N': 'mai-jun-jul 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.0',
  'D1C': '201408',
  'D1N': 'jun-jul-ago 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.8',
  'D1C': '201409',
  'D1N': 'jul-ago-set 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.7',
  'D1C': '201410',
  'D1N': 'ago-set-out 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.6',
  'D1C': '201411',
  'D1N': 'set-out-nov 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.6',
  'D1C': '201412',
  'D1N': 'out-nov-dez 2014',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '6.9',
  'D1C': '201501',
  'D1N': 'nov-dez-jan 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '7.5',
  'D1C': '201502',
  'D1N': 'dez-jan-fev 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '8.0',
  'D1C': '201503',
  'D1N': 'jan-fev-mar 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '8.1',
  'D1C': '201504',
  'D1N': 'fev-mar-abr 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '8.2',
  'D1C': '201505',
  'D1N': 'mar-abr-mai 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '8.4',
  'D1C': '201506',
  'D1N': 'abr-mai-jun 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '8.6',
  'D1C': '201507',
  'D1N': 'mai-jun-jul 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '8.8',
  'D1C': '201508',
  'D1N': 'jun-jul-ago 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '9.0',
  'D1C': '201509',
  'D1N': 'jul-ago-set 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '9.1',
  'D1C': '201510',
  'D1N': 'ago-set-out 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '9.1',
  'D1C': '201511',
  'D1N': 'set-out-nov 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '9.1',
  'D1C': '201512',
  'D1N': 'out-nov-dez 2015',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '9.6',
  'D1C': '201601',
  'D1N': 'nov-dez-jan 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '10.3',
  'D1C': '201602',
  'D1N': 'dez-jan-fev 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '11.0',
  'D1C': '201603',
  'D1N': 'jan-fev-mar 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '11.3',
  'D1C': '201604',
  'D1N': 'fev-mar-abr 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '11.3',
  'D1C': '201605',
  'D1N': 'mar-abr-mai 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '11.4',
  'D1C': '201606',
  'D1N': 'abr-mai-jun 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '11.7',
  'D1C': '201607',
  'D1N': 'mai-jun-jul 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '11.9',
  'D1C': '201608',
  'D1N': 'jun-jul-ago 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '11.9',
  'D1C': '201609',
  'D1N': 'jul-ago-set 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '11.9',
  'D1C': '201610',
  'D1N': 'ago-set-out 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.0',
  'D1C': '201611',
  'D1N': 'set-out-nov 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.1',
  'D1C': '201612',
  'D1N': 'out-nov-dez 2016',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.7',
  'D1C': '201701',
  'D1N': 'nov-dez-jan 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '13.3',
  'D1C': '201702',
  'D1N': 'dez-jan-fev 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '13.9',
  'D1C': '201703',
  'D1N': 'jan-fev-mar 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '13.7',
  'D1C': '201704',
  'D1N': 'fev-mar-abr 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '13.4',
  'D1C': '201705',
  'D1N': 'mar-abr-mai 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '13.1',
  'D1C': '201706',
  'D1N': 'abr-mai-jun 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.9',
  'D1C': '201707',
  'D1N': 'mai-jun-jul 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.7',
  'D1C': '201708',
  'D1N': 'jun-jul-ago 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.5',
  'D1C': '201709',
  'D1N': 'jul-ago-set 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.3',
  'D1C': '201710',
  'D1N': 'ago-set-out 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.1',
  'D1C': '201711',
  'D1N': 'set-out-nov 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '11.9',
  'D1C': '201712',
  'D1N': 'out-nov-dez 2017',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.3',
  'D1C': '201801',
  'D1N': 'nov-dez-jan 2018',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '12.7',
  'D1C': '201802',
  'D1N': 'dez-jan-fev 2018',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '13.2',
  'D1C': '201803',
  'D1N': 'jan-fev-mar 2018',
  'D2C': '4099',
  'D2N': 'Taxa de desocupação, na semana de referência, das pessoas de 14 anos ou mais de idade',
  'D3C': '1',
  'D3N': 'Brasil'},
 {'NC': '1',
  'NN': 'Brasil',
  'MC': '2',
  'MN': '%',
  'V': '13.0',
  'D1C': '201804',

In [8]:
data=response.json()

In [ ]:
df=pd.json_normalize(data)

In [11]:
df.head()

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N
0,Nível Territorial (Código),Nível Territorial,Unidade de Medida (Código),Unidade de Medida,Valor,Trimestre Móvel (Código),Trimestre Móvel,Variável (Código),Variável,Brasil (Código),Brasil
1,1,Brasil,2,%,8.0,201203,jan-fev-mar 2012,4099,"Taxa de desocupação, na semana de referência, ...",1,Brasil
2,1,Brasil,2,%,7.8,201204,fev-mar-abr 2012,4099,"Taxa de desocupação, na semana de referência, ...",1,Brasil
3,1,Brasil,2,%,7.7,201205,mar-abr-mai 2012,4099,"Taxa de desocupação, na semana de referência, ...",1,Brasil
4,1,Brasil,2,%,7.6,201206,abr-mai-jun 2012,4099,"Taxa de desocupação, na semana de referência, ...",1,Brasil

In [16]:
df_st2=df.iloc[1:,:].pivot(index=["D1C", "NN"], columns=["D2N"], values="V")

In [19]:
df_st2=df[["D1C", "NN", "D2N"]]

In [20]:
df_st2

,D1C,NN,D2N
0,Trimestre Móvel (Código),Nível Territorial,Variável
1,201203,Brasil,"Taxa de desocupação, na semana de referência, ..."
2,201204,Brasil,"Taxa de desocupação, na semana de referência, ..."
3,201205,Brasil,"Taxa de desocupação, na semana de referência, ..."
4,201206,Brasil,"Taxa de desocupação, na semana de referência, ..."
...,...,...,...
158,202504,Brasil,"Taxa de desocupação, na semana de referência, ..."
159,202505,Brasil,"Taxa de desocupação, na semana de referência, ..."
160,202506,Brasil,"Taxa de desocupação, na semana de referência, ..."
161,202507,Brasil,"Taxa de desocupação, na semana de referência, ..."
162,202508,Brasil,"Taxa de desocupação, na semana de referência, ..."